/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dlv } from "./dlv.js";

import * as z from "zod";

export interface Env {
  SPEAKEASY_CLIENT_ID?: string | undefined;
  SPEAKEASY_CLIENT_SECRET?: string | undefined;
  SPEAKEASY_TOKEN_URL: string;

  SPEAKEASY_DEBUG?: boolean | undefined;
}

export const envSchema: z.ZodType<Env, z.ZodTypeDef, unknown> = z.object({
  SPEAKEASY_CLIENT_ID: z.string().optional(),
  SPEAKEASY_CLIENT_SECRET: z.string().optional(),
  SPEAKEASY_TOKEN_URL: z.string().default(
    "https://dev-ttwo7r05pkr6nozn.us.auth0.com/oauth/token",
  ),

  SPEAKEASY_DEBUG: z.coerce.boolean().optional(),
});

let envMemo: Env | undefined = undefined;
/**
 * Reads and validates environment variables.
 */
export function env(): Env {
  if (envMemo) {
    return envMemo;
  }

  envMemo = envSchema.parse(
    dlv(globalThis, "process.env") ?? dlv(globalThis, "Deno.env") ?? {},
  );
  return envMemo;
}

/**
 * Clears the cached env object. Useful for testing with a fresh environment.
 */
export function resetEnv() {
  envMemo = undefined;
}
