/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getTodo } from "../funcs/getTodo.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SpeakeasyAuth0Example extends ClientSDK {
  /**
   * List all todos
   */
  async getTodo(
    options?: RequestOptions,
  ): Promise<Array<components.Todo>> {
    return unwrapAsync(getTodo(
      this,
      options,
    ));
  }
}
