/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { todosList } from "../funcs/todosList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Todos extends ClientSDK {
  /**
   * List all todos
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<components.Todo>> {
    return unwrapAsync(todosList(
      this,
      options,
    ));
  }
}
