workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  auto0_client_cred_example_oas:
    inputs:
      - location: openapi.yaml
    registry:
      location: registry.speakeasyapi.dev/walker/walker/auth-0-example-oas
targets:
  auto0_client_cred_example_oas:
    target: typescript
    source: auto0_client_cred_example_oas
